spring:
  datasource:
    url: jdbc:sqlite:billsdb.db
    driverClassName: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

mailjet:
  api-key: YOUR_API_KEY
  api-secret: YOUR_API_SECRET

server:
  port: 8015
