spring:
  datasource:
    url: jdbc:h2:mem:billsdb
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  mail:
    # dummy mail configuration
    host: localhost
    port: 2525
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

server:
  port: 8015
