spring:
  datasource:
    url: jdbc:sqlite:billsdb.db
    driverClassName: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  mail:
    # dummy mail configuration
    host: localhost
    port: 2525
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

server:
  port: 8015
