spring:
  datasource:
    url: jdbc:sqlite:billsdb.db
    driverClassName: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    enabled: true
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

mailjet:
  api-key: "${MAIL_JET_API_KEY}"
  api-secret: "${MAIL_JET_SECRET_KEY}"
  from: "pedroaskale@gmail.com"

server:
  port: 8015
